name: Lint YAML
description: Lint YAML files using yamllint with PowerShell
inputs:
  config_path:
    description: Path to yamllint configuration file
    required: false
    default: .yamllint.yml

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install yamllint
      run: |
        pip install yamllint
      shell: pwsh

    - name: Run yamllint
      run: |
        yamllint -c ${{ inputs.config_path }} .
      shell: pwsh
