name: Lint YAML
description: Lint YAML files using yamllint with PowerShell

# Define input parameters
inputs:
  config_path:
    description: Path to yamllint configuration file
    required: false
    default: .yamllint.yml

runs:
  using: "composite"
  steps:
    # Checkout repository
    - uses: actions/checkout@v3

    # Setup python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Install linter for yaml
    - name: Install yamllint
      run: |
        pip install yamllint
      shell: pwsh

    # Run linting command
    - name: Run yamllint
      run: |
        yamllint -c ${{ inputs.config_path }} .
      shell: pwsh
