name: Template - Lint Yaml Codebase

on:
  workflow_call:
    inputs:
      config_path:
        description: 'Path to yamllint config file'
        required: false
        default: '.yamllint.yml'
        type: string

jobs:
  lint-codebase:
    name: Lint YAML Codebase
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint==1.32.0

      - name: Lint with yamllint
        run: |
          yamllint -c "${{ inputs.config_path }}" .
