name: Lint Python Codebase
description: A composite GitHub Action to lint Python code with flake8

# Define input parameters
inputs:
  config_path:
    description: Path to flake8 config file
    required: false
    default: .flake8

  code_directory:
    description: Directory to scan python files
    required: false
    default: .

runs:
  using: "composite"
  steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup and install python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Setup and import flake8 for python linting
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.1.0
      shell: pwsh

    # Execute linting command
    - name: Run flake8
      run: |
        flake8 ${{ inputs.code_directory }} `
          --config=${{ inputs.config_path }} `
          --count `
          --show-source `
          --statistics
      shell: pwsh
