name: "Run Behave BDD Tests"
description: "Checks out code, sets up Python, installs dependencies, and runs Behave tests."

# Define action inputs
inputs:
  features_path:
    description: "Path to the Behave features directory"
    required: false
    default: "features"

  requirements_path:
    description: "Path to the requirements.txt file"
    required: false
    default: "requirements.txt"

runs:
  using: "composite"
  steps:
    # Checkout codebase
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Instal dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements_path }}
      shell: bash

    # Execute python behave BDD test
    - name: Run Behave tests
      run: behave ${{ inputs.features_path }} --format=plain --outfile=behave.log
      shell: bash
