name: "Run PyTest Tests"
description: "Checks out code, sets up Python, installs dependencies, and runs PyTest tests."

# Define action inputs
inputs:
  testing_directory:
    description: "Path to the pytest directory"
    required: false
    default: "."

  toml_dependencies:
    description: "List of toml dependencies"
    required: false
    default: "."
  
  secrets:
    codecov_token:
      description: 
      required: false
      default: ""

runs:
  using: "composite"
  steps:
    # Checkout codebase
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Instal dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ${{ inputs.toml_dependencies }}
      shell: bash

    # Execute python pytests
    - name: Run PyTests tests
      run: pytest --cov --cov-branch --cov-report=xml
      shell: bash

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}