name: Deploy Terraform

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

concurrency:
  group: deploy-terraform
  cancel-in-progress: false

jobs:
  # Terraform plan
  plan:
    name: Plan
    uses: ./.github/workflows/template-plan-apply-terraform.yml
    with:
      tf_directory: 'infra'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  # Terraform apply
  apply:
    needs: plan
    if: needs.plan.outputs.has_changes == 'true'
    name: Apply
    uses: ./.github/workflows/template-plan-apply-terraform.yml
    with:
      should_apply: 'true'
      release_environment: 'PROD'
      tf_directory: 'infra'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
