name: Deploy Terraform

on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

jobs:
  plan:
    name: Terraform Plan
    uses: ./.github/workflows/template-plan-apply-terraform.yml
    with:
      tf_state_container_name: 'tfstate'
