name: Deploy Terraform

on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

jobs:
  plan:
    name: Plan
    uses: ./.github/workflows/template-plan-apply-terraform.yml
    with:
      tf_directory: 'infra'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  apply:
    needs: plan
    name: Apply
    uses: ./.github/workflows/template-plan-apply-terraform.yml
    with:
      should_apply: 'true'
      release_environment: 'PROD'
      tf_directory: 'infra'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
