name: Deploy Terraform

on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

jobs:
  plan:
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    # name: Terraform Plan
    # uses: ./.github/workflows/template-plan-apply-terraform.yml
    # with:
    #   tf_state_container_name: 'tfstate'
