name: Deploy Terraform

on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

jobs:
  plan:
    name: Terraform Plan
    uses: ./.github/workflows/template-plan-apply-terraform.yml
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }} 
    with:
      tf_state_resource_group_name: tfstate-rg
      tf_state_storage_account: powellrhystfstate
      tf_state_container_name: tfstate
      tf_state_key: powellrhys
