name: Deploy Terraform

# Define pipeline trigger criteria
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'feature/**'

jobs:
  # Execute plan
  plan:
    name: Plan
    uses: ./.github/workflows/template-plan-apply-terraform.yml
    with:
      tf_directory: 'infra'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  # Execute apply
  apply:
    needs: plan
    name: Apply
    uses: ./.github/workflows/template-plan-apply-terraform.yml
    with:
      should_apply: 'true'
      release_environment: 'PROD'
      tf_directory: 'infra'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
