name: Lint Yaml Codebase

# Define trigger criteria
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

concurrency:
  group: lint-codebase
  cancel-in-progress: false

jobs:
  # Lint yaml codebase
  lint-yaml:
    name: Lint Yaml Pipelines
    uses: ./.github/workflows/template-lint-yaml.yml
    with:
      config_path: '.yamllint.yml'
