name: Lint Yaml Codebase

on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/lint-yaml
        with:
          config_path: .yamllint.yml
