name: Lint Yaml Codebase

on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

jobs:
  lint:
    uses: ./github-actoins/lint-yaml-templates.yml
    with:
      config_path: '.yamllint.yml'
