name: Lint Yaml Codebase

# Define trigger criteria
on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

jobs:
  # Lint yaml codebase
  lint-yaml:
    name: Lint Yaml Pipelines
    uses: ./.github/workflows/template-lint-yaml.yml
    with:
      config_path: '.yamllint.yml'
