name: Lint Yaml Codebase

on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

jobs:
  lint:
    uses: ./.github/workflows/templates/lint-yaml-templates.yml@refs/heads/main
    with:
      config_path: '.yamllint.yml'
