name: Lint Yaml Codebase

# Define trigger criteria
on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

jobs:
  lint:
    name: Lint Yaml
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Execute linting action
      - uses: ./.github/actions/lint-yaml
        with:
          config_path: .yamllint.yml
