name: Template - Plan & Apply Terraform

on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true
    inputs:
      tf_state_resource_group_name:
        description: 'Blob storage resource group'
        required: true
        type: string
      tf_state_storage_account:
        description: 'Blob storage storage account name'
        required: true
        type: string
      tf_state_container_name:
        description: 'Blob storage container name'
        required: true
        type: string
      tf_state_key:
        description: 'Terraform state file key'
        required: true
        type: string

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ inputs.tf_state_resource_group_name }}" \
            -backend-config="storage_account_name=${{ inputs.tf_state_storage_account }}" \
            -backend-config="container_name=${{ inputs.tf_state_container_name }}" \
            -backend-config="key=${{ inputs.tf_state_key}}"
