name: Template - Lint Python Codebase

on:
  workflow_call:
    inputs:
      config_path:
        description: Path to flake8 config file
        required: false
        default: ".flake8"
        type: string

      code_directory:
        description: Directory to scan python files
        required: false
        default: "."
        type: string

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup python
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      # Install flake8
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.1.0

      # Run flake8 linter on python codebase
      - name: Run flake8
        run: |
          flake8 ${{ inputs.code_directory }} \
            --config=${{ inputs.config_path }} \
            --count \
            --show-source \
            --statistics
