name: Template - Lint Python Codebase

on:
  workflow_call:
    inputs:
      config_path:
        description: 'Path to flake8 config file'
        required: false
        default: '.flake8'
        type: string
      code_directory:
        description: 'Directory to scan python files'
        required: false
        default: '.'
        type: string


jobs:
  lint-codebase:
    name: Lint YAML Codebase
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.1.0

      # Lint python codebase with flake8
      - name: Lint with flake8
        run: |
          flake8 "${{ inputs.code_directory }}" \
            --config=/path/to/"${{ inputs.config_path }}" \
            --count \
            --show-source \
            --statistics
