name: Lint YAML

on:
  workflow_call:
    inputs:
      config_path:
        description: Path to yamllint configuration file
        required: false
        default: ".yamllint.yml"
        type: string

jobs:
  yamllint:
    name: Lint YAML files
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup python
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      # Install yamllint package
      - name: Install yamllint
        run: pip install yamllint==1.32.0

      # Execute yamllint linter
      - name: Run yamllint
        run: yamllint -c ${{ inputs.config_path }} .
