name: Terraform Plan & Apply

# Define workflow call and input parameters and secrets
on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true
    inputs:
      release_environment:
        description: 'GitHub environment for release'
        default: ''
        type: string

      should_apply:
        description: 'Whether to apply the plan'
        default: 'false'
        type: string

      tf_directory:
        description: 'Terraform code directory'
        required: false
        default: '.'
        type: string

      tf_vars_file_name:
        description: 'Name of tfvars file'
        required: false
        type: string

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: ${{ inputs.release_environment }}
    permissions:
      contents: read
      packages: read

    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Login to azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Setup terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.2

      # Collect azure credentials for terraform remote config
      - name: Export Azure credentials for Terraform
        run: |
          echo '${{ secrets.AZURE_CREDENTIALS }}' > azurecreds.json
          echo "ARM_CLIENT_ID=$(jq -r .clientId azurecreds.json)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq -r .clientSecret azurecreds.json)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId azurecreds.json)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(jq -r .tenantId azurecreds.json)" >> $GITHUB_ENV
        shell: bash

      # Initialize terraform
      - name: Terraform Init
        run: |
          terraform -chdir="${{ inputs.tf_directory }}" init

      # Validate terraform
      - name: Terraform Validate
        run: terraform -chdir="${{ inputs.tf_directory }}" validate

      # Run terraform plan
      - name: Terraform Plan
        shell: pwsh
        run: |
          $varFileArg = ""
          if ("${{ inputs.tf_vars_file_name }}" -ne "") {
            $varFileArg = "-var-file='${{ inputs.tf_vars_file_name }}'"
          }

          terraform `
            -chdir="${{ inputs.tf_directory }}" plan `
            $varFileArg -out=tfplan

      # Apply terraform
      - name: Terraform Apply (if enabled)
        if: ${{ inputs.should_apply == 'true' }}
        run: terraform -chdir="${{ inputs.tf_directory }}" apply tfplan
