name: Template - Build and Push Docker Image

# Define trigger condition and input variables and secrets
on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the Docker image'
        required: true
        type: string

      docker_file_path:
        description: 'Path to the Dockerfile'
        required: true
        type: string

    secrets:
      docker_password:
        description: 'Docker Hub password'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push Container
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to docker hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.docker_password }}

      # Build and push container to dockerhub
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ github.actor }}/${{ inputs.image_name }} `
                       -f ${{ inputs.docker_file_path }} .

          docker push ${{ github.actor }}/${{ inputs.image_name }}:latest
        shell: pwsh
