name: Run Behave BDD Tests
on:
  workflow_call:
    inputs:
      features_path:
        description: "Path to the Behave features directory"
        required: false
        default: "features"
        type: string

      toml_dependencies:
        description: "List of toml dependencies"
        required: false
        type: string
        default: "."

jobs:
  behave-tests:
    name: Behave BDD Tests
    runs-on: ubuntu-latest

    steps:
        # Checkout codebase
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ${{ inputs.toml_dependencies }}

      # Run behave testing
      - name: Run Behave tests
        run: behave ${{ inputs.features_path }} --format=plain --outfile=behave.log
