name: "Run PyTest Tests"

on:
  workflow_call:
    inputs:
      toml_dependencies:
        description: "List of toml dependencies"
        required: false
        type: string
        default: "."

    secrets:
      codecov_token:
        description: "Codecov upload token"
        required: true

jobs:
  pytest:
    name: PyTest
    runs-on: ubuntu-latest
    steps:
      # Checkout codebase
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ${{ inputs.toml_dependencies }}

      # Execute pytest tests and generate code coverage report
      - name: Run PyTests
        run: pytest --cov --cov-branch --cov-report=xml

      # Upload coverage reports to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
